testapp/urls.py
from django.urls import path
from . import views

app_name='testapp'
urlpatterns=[
    path('',views.index_template,name='index_template'),
    path('change',views.change_graph,name='change_graph'),
]

testproject/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testapp.urls')),
]

testapp/models.py
from django.db import models

# Create your models here.
class Day(models.Model):
    year = models.DateField('年月日',max_length=255)
    average = models.FloatField('平均気温')
    max = models.FloatField('最高気温')
    min = models.FloatField('最低気温')

class Month(models.Model):
    year = models.IntegerField('年')
    month = models.IntegerField('月')
    average = models.FloatField('平均気温')
    max_average = models.FloatField('最高平均気温')
    min_average = models.FloatField('最低平均気温')
    max = models.FloatField('最高気温')
    min = models.FloatField('最低気温')

class Year():
    year = models.IntegerField('年')
    average = models.FloatField('平均気温')
    max_average = models.FloatField('最高平均気温')
    min_average = models.FloatField('最低平均気温')
    max = models.FloatField('最高気温')
    min = models.FloatField('最低気温')

testapp/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from django.http import JsonResponse

import pandas as pd
from datetime import datetime as dt

from PIL import Image
from pathlib import Path          
from django.contrib.auth.models import User
import copy                    

from django.shortcuts import render
import io
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import base64

#最初に呼び出される
def index_template(request):
    
    df = pd.read_csv('C:\\Users\\user\\python-2023\\testproject\\static\\csv\\year_date.csv')
    plt.figure(figsize=(10,5))
    plt.plot(df['date'],df['average'])
    plt.xlabel('year')
    plt.ylabel('temperature')
    plt.grid()

    graph = get_image()
    return render(request, 'index.html',{'graph': graph})

#グラフを作成
def graph_create(x_top,x_end,y_select,df):

    views_df = df[(df['date'] >= x_top) & (df['date'] <= x_end)]
    plt.figure(figsize=(10,5))
    plt.plot(views_df["date"],views_df[y_select])

    plt.xlabel('date')
    plt.ylabel('temperature')
    plt.grid()

    graph = get_image()
    return graph

#グラフを変える
def change_graph(request):
    x_option = request.POST['x_option']
    y_select = request.POST['y_select']
    x_top = request.POST['x_top']
    x_end = request.POST['x_end']

    if x_option == "year":
        df = pd.read_csv('C:\\Users\\user\\python-2023\\testproject\\static\\csv\\year_date.csv')
        x_top = int(request.POST['x_top'])
        x_end = int(request.POST['x_end'])
    elif x_option == "month":
        df = pd.read_csv('C:\\Users\\user\\python-2023\\testproject\\static\\csv\\mth_date.csv')
        df['date'] = pd.to_datetime(df['date'].astype(str))
        print(x_top)
    elif x_option == "day":
        df = pd.read_csv('C:\\Users\\user\\python-2023\\testproject\\static\\csv\\day_date.csv')
        df['date'] = pd.to_datetime(df['date'].astype(str))

    
    graph = graph_create(x_top, x_end, y_select, df)
    return JsonResponse({'graph': graph})

#画像にする
def get_image():
 buffer = io.BytesIO()
 plt.savefig(buffer, format='png')
 image_png = buffer.getvalue()
 graph = base64.b64encode(image_png)
 graph = graph.decode('utf-8')
 buffer.close()
 return graph

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <title>テストサイト</title>
</head>

<body>
    <p>This is test</p>
    <!--折れ線グラフ表示-->
    <img id="graph" src="data:image/png;base64, {{ graph | safe }}" alt="">

    <form name="checkes" action='' method="post">{% csrf_token %}
        <!--データの種類の選択。ラジオボタンにより複数選択可能 -->
        <p class="y_DataSelect">Y軸のデータを選んでください</p>

        <div id="averages">
            <input type="radio" id="average" name="y_data" value="平均気温" checked>
            <label for="average">平均気温</label>

            <input type="radio" id="max_average" name="y_data" value="最高平均気温">
            <label for="max_average">最高平均気温</label>

            <input type="radio" id="min_average" name="y_data" value="最低平均気温">
            <label for="min_average">最低平均気温</label>

            <input type="radio" id="max" name="y_data" value="最高気温">
            <label for="max">最高気温</label>

            <input type="radio" id="min" name="y_data" value="最低気温">
            <label for="min">最低気温</label>
        </div>

        <!-- x軸の期間入力 -->
        <p class="x_DataSelect">表示するデータの期間を記入してください。データは1946年～2022年まで選べます<em>※半角で入力してください</em><br>
            <!--年と月のプルダウンメニュー-->
        <p>
            <select id="topyearSelect" name="topyearSelect"></select>年
            ~
            <select id="endyearSelect" name="endyearSelect"></select>年<br>

            <select id="topmonthSelect" name="topmonthSelect"></select>月
            ~
            <select id="endmonthSelect" name="endmonthSelect"></select>月
        </p>
        </p>

        <label><input type="radio" name="x_option" id="year" checked>年ごと</label>
        <label><input type="radio" name="x_option" id="month">月ごと</label>
        <label><input type="radio" name="x_option" id="day">日ごと</label>

        <p>
            <button type="button" onclick="buttonClick()">予測</button>
        </p>
    </form>
    <a id="log">変数確認</a>
    <!-- 以下Javascript  外部jsの読み込み時にURLの変換ができていなかったのでHTMLに埋め込みました。
     404は解決し403エラーとなりました。CSRF対策後403から500エラーになりました。 -->
    {% block extra_js %}
    <!-- <script src="{% static 'JavaScripts/main.js' %}"></script> -->
    <script>
        //月毎の日数
        let month_days = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
        //フォームの取得
        const form = document.forms.checkes;

        var vals = []; // 配列を定義

        //各radiobuttonのドキュメント
        let average = document.getElementById("average");
        let max_average = document.getElementById("max_average");
        let min_average = document.getElementById("min_average");
        let max = document.getElementById("max");
        let min = document.getElementById("min");
        let averages = document.getElementById('averages');
        let day_date = document.getElementById('day_date');

        function graphDataSet() {

        }

        document.getElementById('log').onclick = function() {
            console.log(x_date_top);
        }

        //プルダウンメニュー
        const selectBox1 = document.getElementById('topyearSelect');
        const selectBox2 = document.getElementById('endyearSelect');
        const selectBox3 = document.getElementById('topmonthSelect');
        const selectBox4 = document.getElementById('endmonthSelect');
        const startYear = 1946;
        const endYear = 2022;
        const startMonth = 1;
        const endMonth = 12;

        //初めの年のプルダウンメニュー
        for (let year = startYear; year <= endYear; year++) {
            const option1 = document.createElement('option');
            option1.value = year;
            option1.textContent = year;
            selectBox1.appendChild(option1);

            //終わりの年のプルダウンメニュー
            const option2 = document.createElement('option');
            option2.value = year;
            option2.textContent = year;
            selectBox2.appendChild(option2);
        }

        //初めの月のプルダウンメニュー
        for (let month = startMonth; month <= endMonth; month++) {
            const option1 = document.createElement('option');
            option1.value = month;
            option1.textContent = month;
            selectBox3.appendChild(option1);

            //終わりの月のプルダウンメニュー
            const option2 = document.createElement('option');
            option2.value = month;
            option2.textContent = month;
            selectBox4.appendChild(option2);
        }

        function buttonClick() {
            const y_data = document.querySelector('input[name="y_data"]:checked');
            const topyear = selectBox1.value;
            const endyear = selectBox2.value;
            const topmonth = selectBox3.value;
            const endmonth = selectBox4.value;
            const x_option = document.querySelector('input[name="x_option"]:checked');
            var x_top = "";
            var x_end = "";

            //0624 CSRFトークン
            var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

            if (topyear > endyear) {
                alert("入力値に誤りがありました。");
            } else if (topyear == endyear && topmonth > endmonth) {
                alert("入力値に誤りがありました。");
            } else {
                if (x_option.id == "year") {
                    x_top = topyear;
                    x_end = endyear;
                } else if (x_option.id == "month") {
                    x_top = topyear + "-" + topmonth;
                    x_end = endyear + "-" + endmonth;
                } else if (x_option.id == "day") {
                    x_top = topyear + "-" + topmonth + "-1";
                    x_end = endyear + "-" + endmonth + "-1";
                }

                $.ajax({
                    url: `{% url 'testapp:change_graph' %}`,
                    headers: {
                        'X-CSRFToken': csrftoken
                    },
                    type: 'POST',
                    data: {
                        'x_top': x_top,
                        'x_end': x_end,
                        'x_option': x_option.id,
                        'y_select': y_data.id,
                    },
                    dataType: 'json',
                    success: function(response) {
                        document.getElementById('graph').src = 'data:image/png;base64,' + response.graph;
                    },
                    error: function(xhr, status, error) {
                        console.error(xhr.responseText);
                    }
                });
            }
        }
    </script>
    {% endblock %}
</body>
</html>